# Generated by Django 5.2.10 on 2026-06-17 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='health_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CivicMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('total_complaints', models.IntegerField()),
                ('closed_complaints', models.IntegerField()),
                ('escalated_complaints', models.IntegerField()),
                ('avg_resolution_days', models.FloatField()),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='api.ward')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('ward', 'year')},
            },
        ),
    ]
