# Generated by Django 5.2.10 on 2026-06-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ward_health_score_civicmetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='civicmetrics',
            name='avg_councillors',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='civicmetrics',
            name='per_capita_complaints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='civicmetrics',
            name='per_capita_deliberations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='civicmetrics',
            name='total_deliberations',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='civicmetrics',
            name='avg_resolution_days',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='civicmetrics',
            name='closed_complaints',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='civicmetrics',
            name='escalated_complaints',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='civicmetrics',
            name='total_complaints',
            field=models.IntegerField(default=0),
        ),
    ]
