# Generated by Django 5.2.10 on 2026-06-18 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_civicmetrics_avg_councillors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('pothole', 'Potholes'), ('water', 'Water Supply'), ('drainage', 'Drainage'), ('garbage', 'Garbage'), ('streetlight', 'Street Lights'), ('road', 'Roads'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='api.ward')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
