# Generated by Django 5.2.10 on 2026-06-18 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_complaint_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WardPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateField(auto_now_add=True)),
                ('predicted_risk', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk')], max_length=20)),
                ('predicted_complaints', models.IntegerField()),
                ('predicted_health_score', models.FloatField(blank=True, null=True)),
                ('recommendation', models.TextField(blank=True)),
                ('model_version', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='api.ward')),
            ],
            options={
                'verbose_name': 'Ward Prediction',
                'verbose_name_plural': 'Ward Predictions',
                'ordering': ['-prediction_date'],
            },
        ),
    ]
