# Generated by Django 5.2.15 on 2026-06-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_wardprediction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='user',
        ),
        migrations.AlterField(
            model_name='wardprediction',
            name='prediction_date',
            field=models.DateField(),
        ),
    ]
