# Generated by Django 5.2.10 on 2026-06-21 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_complaint_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wardprediction',
            name='predicted_complaints_lower',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wardprediction',
            name='predicted_complaints_upper',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wardprediction',
            name='top_features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PortalMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('total_complaints', models.IntegerField(default=0)),
                ('resolved_complaints', models.IntegerField(default=0)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_metrics', to='api.ward')),
            ],
            options={
                'verbose_name_plural': 'Portal Metrics',
                'unique_together': {('ward', 'year')},
            },
        ),
    ]
