# Generated by Django 5.2.10 on 2026-06-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_complaint_resolved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='sender_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='source',
            field=models.CharField(choices=[('portal', 'Web Portal'), ('whatsapp', 'WhatsApp')], default='portal', max_length=20),
        ),
    ]
